### ISSUE TITLE
Add 'open' azure pipeline under philips-software organisation.

### ISSUE THREAD

**Issue by bartgolsteijn** [philips-software/Gherkin2Mtm#10]
Add a simple, publicly visible azure pipeline under the philips-software organisation.
Use `azure-pipelines.yml` to define this.

**Comment by krmeda** [comment]
I can help @bart. I would probably need access to the Azure DevOps account.

**Comment by puttagunta** [comment]
@bartgolsteijn sorry for missing your comment, at the first place. Sure, will do that. Can you or someone grant me access to that organization?
@krmeda if you get access to that, go ahead.

**Comment by bartgolsteijn** [comment]
Added @puttagunta to the Gherkin2Mtm team on Azure DevOps.
